FROM alpine
LABEL Maintainer="Katayoun Borojerdi <kborojerdi@ischool.berkeley.edu" \
      Description="Lightweight Mosquitto MQTT server based on Alpine Linux."

RUN apk update && apk upgrade
RUN apk add mosquitto mosquitto-clients

# Expose MQTT port
EXPOSE 1883

# ENV PATH /usr/sbin:$PATH

# CMD ["mosquitto"]
# CMD /usr/sbin/mosquitto -c /conf/mosquitto.conf
ENTRYPOINT ["/usr/sbin/mosquitto"]
