version: "3.7"
services:

  mqtt-broker:
    image: mqtt-broker
    container_name: mqtt-broker
    restart: always
    ports:
      - "1883"
    networks:
      - mosquitto

  mqtt-forwarder:
    image: mqtt-forwarder
    container_name: mqtt-forwarder
    command: python mqtt.py
    ports:
      - "1883"
    networks:
      - mosquitto
    depends_on: 
      - mosquitto

  video_capture:
    image: video_capture
    container_name: video_capture
    environment:
      - DISPLAY
    volumes:
      - /tmp:/tmp
    privileged: true
    command: bash
    ports:
      - "1883"
    networks:
      - mosquitto
    depends_on: 
      - forwarder
    tty: true

networks:
  mosquitto:
    name: mosquitto
