version: "3"
services:

  mosquitto:
    image: alpine-mqtt
    container_name: mosquitto
    restart: always
    ports:
            - 1883:1883
    networks:
      - mosquitto
  client:
    image: image_capture
    container_name: client
    command: python mqtt_sub_save.py
    #    ports:
            #      - 1883:1883
    restart: 'always'
    networks:
      - mosquitto
    depends_on:
      - mosquitto
    tty: true
    volumes:
      - /mnt/mybucket:/mnt/mybucket

networks:
  mosquitto:
