version: "3"
services:

  mqtt-broker:
    image: mqtt-broker
    container_name: mqtt-broker
    restart: always
    ports:
      - 1883:1883
    networks:
      - mosquitto
      
  image_saver:
    image: image_saver
    container_name: image_saver
    command: python mqtt_sub_save.py
    ports:
      - "1883"
    networks:
      - mosquitto
    depends_on:
      - mosquitto
    tty: true
    volumes:
      - /mnt/mybucket:/mnt/mybucket

networks:
  mosquitto:
      name: mosquitto
